### ISSUE TITLE
Support for Relationships in New-PBIDataSet

### ISSUE THREAD

**Issue by darrenjrobinson** [DevScope/powerbi-powershell-modules#13]
The PowerBI API supports Relationships on Datasets https://msdn.microsoft.com/en-us/library/mt742155.aspx
Can this be added to the New-PBIDataSet cmdlet ?

**Comment by RuiRomano** [comment]
Yes, off course
Only need to find time to do that :), very busy weeks lately.
If you want to make the pull request you are more that welcome ;). I will try to update the module next month.
Sorry.








Enviado a partir do meu smartphone Samsung Galaxy.<div>
</div><div>
</div><div>-------- Mensagem original --------</div><div>De: darrenjrobinson <notifications@github.com> </div><div>Data: 27/08/16  14:50  (GMT+00:00) </div><div>Para: DevScope/powerbi-powershell-modules <powerbi-powershell-modules@noreply.github.com> </div><div>Assunto: [DevScope/powerbi-powershell-modules] Support for Relationships in New-PBIDataSet (#13) </div><div>
</div>
The PowerBI API supports Relationships on Datasets https://msdn.microsoft.com/en-us/library/mt742155.aspx
Can this be added to the New-PBIDataSet cmdlet ?

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/DevScope/powerbi-powershell-modules/issues/13

**Comment by darrenjrobinson** [comment]
Hi Rui, 
I've realized there is no change required. Just have to tell PowerBIPS to use the Beta API which has Relationships available. 
I've documented creating relationships via PowerBI here https://blog.kloud.com.au/2016/08/31/leveraging-the-powerbi-beta-api-for-creating-powerbi-tables-with-relationships-via-powershell/ 

DR
